/* Autogenerated by png2wx.pl on Fri Jul  2 14:28:45 2010 */
#ifndef VROOMGIS_BITMAP
#define VROOMGIS_BITMAP 1

#include <wx/wxprec.h>

#ifndef WX_PRECOMP

#	include <wx/wx.h>

#endif

extern void vroomgis_initialize_images(void);

extern void vroomgis_clear_images(void);

// main bitmap
extern wxBitmap *_img_vroomgis;
extern wxBitmap *_img_vroomgis_sml; // 32x32 px

// cursors
extern wxBitmap *_img_cursor_editing;
extern wxBitmap *_img_cursor_zoomin;
extern wxBitmap *_img_cursor_zoomout;

extern wxBitmap *_img_tree_folder_on;
extern wxBitmap *_img_tree_folder_off;


#endif /* VROOMGIS_BITMAP */
