/* Autogenerated by png2wx.pl on Mon Feb 13 22:05:03 2017 */
#ifndef VROOMGIS_TOOLBMP_H
#define VROOMGIS_TOOLBMP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void vroomgis_initialize_images_toolbar(void);
extern void vroomgis_uninitialize_images_toolbar(void);

extern wxBitmap *_img_toolbar_select;
extern wxBitmap *_img_toolbar_pan;
extern wxBitmap *_img_toolbar_zoom;
extern wxBitmap *_img_toolbar_zoomfull;
extern wxBitmap *_img_toolbar_edit;
extern wxBitmap *_img_toolbar_modify;

#endif /* VROOMGIS_TOOLBMP_H */
