 /* Autogenerated by png2wx.pl on Fri Jul  2 14:28:45 2010 */
#ifndef VROOMGIS_BITMAP
#define VROOMGIS_BITMAP 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void vroomgis_initialize_images(void);
extern void vroomgis_clear_images(void);

extern wxBitmap *_img_vroomgis;

#endif /* VROOMGIS_BITMAP */
