/* Autogenerated by png2wx.pl on Mon Feb 13 22:39:45 2017 */
#ifndef VROOMDRAWER_TOOLBMP_H
#define VROOMDRAWER_TOOLBMP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

extern void vroomdrawer_initialize_images(void);

extern wxBitmap* _img_toolbar_add_memory;

#endif /* VROOMDRAWER_TOOLBMP_H */
